[package]
name = "jisho_ing"
version = "0.1.0"
authors = ["wanghe9 <wanghe9@vipkid.com.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
